// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/zeek-r/weather-monster/models"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: toInsert
func (_m *Service) Create(toInsert *models.Temperature) error {
	ret := _m.Called(toInsert)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Temperature) error); ok {
		r0 = rf(toInsert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
