// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/zeek-r/weather-monster/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: toInsert
func (_m *Repository) Create(toInsert *models.Temperature) error {
	ret := _m.Called(toInsert)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Temperature) error); ok {
		r0 = rf(toInsert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetForecastByID provides a mock function with given fields: id
func (_m *Repository) GetForecastByID(id uint) (*models.Forecast, error) {
	ret := _m.Called(id)

	var r0 *models.Forecast
	if rf, ok := ret.Get(0).(func(uint) *models.Forecast); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Forecast)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
