// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/zeek-r/weather-monster/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: toInsert
func (_m *Repository) Create(toInsert *models.City) error {
	ret := _m.Called(toInsert)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.City) error); ok {
		r0 = rf(toInsert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: toDelete
func (_m *Repository) DeleteByID(toDelete *models.City) error {
	ret := _m.Called(toDelete)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.City) error); ok {
		r0 = rf(toDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: toUpdate
func (_m *Repository) Update(toUpdate *models.City) error {
	ret := _m.Called(toUpdate)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.City) error); ok {
		r0 = rf(toUpdate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
